#! /usr/bin/env node

const chalk = require('chalk')
const commander = require('commander')

const logger = require('../lib/logger')
const Server = require('./server/Server')

const nodeVersion = process.versions.node

// Handle program init
commander
  .arguments('<cmd> [setting]')
  .usage('<cmd> [settings...]')
  .on('--help', function () {
    logger.print(
      [
        chalk.gray('Examples:'),
        '',
        ' $ iai watch',
      ].join('\n') + logger.getCommonAppendix()
    )
  })
  .parse(process.argv)

if (nodeVersion !== '4.3.2') {
  logger.logClean('\n')
  logger.logClean(chalk.yellow('-----------------------------------------------------------'))
  logger.logClean(chalk.yellow.bold('WARNING!'), 'You are not using Node.js version', chalk.blue.bold('4.3.2'))
  logger.logClean(chalk.gray('\nCurrent detected version:'), chalk.yellow.bold(`${nodeVersion}`))
  logger.logClean('\n')
  logger.logClean('See docs:', chalk.blue.underline('http://docs.init.ai/reference/cli.html'))
  logger.logClean(chalk.yellow('-----------------------------------------------------------'))
  logger.logClean('\n')
}

// Run program
new Server()
